# Uncomment this line to define a global platform for your project
 platform :ios, '10.0'

target 'OneDriveSDK' do
#    pod 'MSAL' #, '~> 1.2'
    pod 'ADAL'#, '~> 4.0'
    pod 'Base32' #, '~> 1.1'
end

target 'OneDriveSDKTests' do
    pod 'OCMock'
end

